#include "stdafx.hpp"
#include <unordered_set>

#include "Converter/IW7/Assets/IwiImage.hpp"
#include "Converter/IW7/Assets/PackedImage.hpp"
#include "IW7/Assets/GfxImage.hpp"
#include "Material.hpp"
#include "GfxImage.hpp"

//#include "IW7/Assets/Material.hpp"

// r0 - replace
// c0 - color map
// n0 - normal map
// s0 - specular map
// p0 - parallax
// a0 - Add
// b0 - Blend
// d0 - Detail
// t0 - transparent ? (means that its replace + alpha test >= 128 meaning either full / no transparency per pixel)
// q0 - (don't know the word, it's a detail map for normals)
// 
// _ct_ = colorTint

namespace ZoneTool
{
	namespace IW7
	{
		enum techset_map_type_e
		{
			regular,
			color_tint,
			// The p0 form of the same technique: two slots, semantic 14 _packed_cs and
			// semantic 15 _packed_ng, no separate specular. Only fill this in where the p0
			// techset is known to exist - a material repointed at a technique the linker
			// cannot resolve fails the build, and one left on a three-slot technique with a
			// two-entry table walks off the end of it. Leave empty to keep a techset on the
			// unpacked path, which IW7 uses too: 243 stock materials across 84 unpacked
			// techsets bind IW3-shared assets that way.
			//
			// Leave it empty for anything that carries alpha, whatever its slots. _packed_cs
			// spends the colour map's alpha on specular, but a blend technique reads that
			// channel as opacity and an atest one as the cutout mask, so packing replaces the
			// transparency with the specular value - glass turns solid, foliage loses its
			// cutout. Stock agrees: atest sits on p0 0 times out of 2124 and blendadd 7 out
			// of 1168, against 11527 of 38861 for replace. Where stock packs a transparent
			// material it uses pa0 - the same two slots plus a separate alpha map at semantic
			// 16 (hash 2771134132, 2360 of them binding an _a image) - which we have nothing
			// to fill, so the unpacked technique is the right target.
			packed,
			// The pa0 form: the same two packed slots plus an opacity map at semantic 16. This
			// is the target for a technique that reads alpha, because _packed_cs spends its own
			// alpha on reflectance and so cannot carry any. Stock keeps the two strictly apart -
			// alpha-test sits on p0 0 times out of 2124, blendadd 7 out of 1168 - so a techset
			// has one form or the other, never both.
			packed_alpha,
			count,
		};

		struct techset_map_s
		{
			std::string techset[techset_map_type_e::count];
		};

		techset_map_s make_techset_map(const std::string& regular, const std::string& color_tint = {},
			const std::string& packed = {}, const std::string& packed_alpha = {})
		{
			techset_map_s map;
			map.techset[techset_map_type_e::regular] = regular;
			map.techset[techset_map_type_e::color_tint] = color_tint;
			map.techset[techset_map_type_e::packed] = packed;
			map.techset[techset_map_type_e::packed_alpha] = packed_alpha;
			return map;
		}

		std::unordered_map<std::string, techset_map_s> mapped_techsets =
		{
			// Generated by tools/iw3-to-iw7-techsets/generate.py from CoD4's raw/techsets and the slot
			// signatures of stock IW7 materials. Do not hand-edit the generated rows; change the
			// generator and re-run it.
			//
			// IW5 spells its model and world techsets <prefix>_<blend><features>, where the blend letter
			// is r0 (replace), b0 (blend) or t0 (alpha test) and the features are c0 colour, n0 normal,
			// s0 specular, d0 detail. The blend letter selects replace_/ndw_blend_/atest_ in the IW7
			// name, which are different techniques, so a candidate is only ever considered within its
			// own blend.
			//
			// IW7 has far fewer of these, so several IW5 variants collapse onto one target and any
			// feature IW7 has no technique for is dropped, least-important first (d0, then n0, then s0).
			// Colour-only and colour/normal model materials, plus opaque/blended world materials, use
			// the stock i0c0s0n0 target; missing normal/specular slots receive defaults below.
			// A technique binds its arguments by scanning the texture table for each hash with no bounds
			// check, so every target here was accepted only because its slot set - read off the stock
			// materials that ship on it - is one the converter can fill. Anything unlisted falls back to
			// 2d, which is wrong but safe.
			//
			// The third and fourth entries are the packed forms: p0 for an opaque technique, pa0 for one
			// that reads alpha. They are mutually exclusive - see techset_map_type_e above.

			{"mc_l_b0c0",                   {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_b0c0d0",                 {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_b0c0d0n0",               {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_b0c0d0n0s0",             {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_b0c0d0s0",               {"mo_l_sm_ndw_blend_i0c0s0"}},
			{"mc_l_b0c0n0",                 {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_b0c0n0s0",               {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_b0c0s0",                 {"mo_l_sm_ndw_blend_i0c0s0"}},
			{"mc_l_flag_t0c0",              {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_flag_t0c0n0",            {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_flag_t0c0n0s0",          {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_flag_t0c0s0",            {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_r0c0",                   {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_r0c0d0",                 {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_r0c0d0n0",               {"mo_l_sm_replace_i0c0n0d0"}},
			{"mc_l_r0c0d0n0s0",             {"mo_l_sm_replace_i0c0s0n0d0", "", "mo_l_sm_replace_i0c0s0n0d0p0"}},
			{"mc_l_r0c0d0s0",               {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_r0c0n0",                 {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_r0c0n0s0",               {"mo_l_sm_replace_i0c0s0n0", "", "mo_l_sm_replace_i0c0s0n0p0"}},
			{"mc_l_r0c0s0",                 {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_scroll_b0c0",            {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_scroll_b0c0d0",          {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_scroll_b0c0d0n0",        {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_scroll_b0c0d0n0s0",      {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_scroll_b0c0d0s0",        {"mo_l_sm_ndw_blend_i0c0s0"}},
			{"mc_l_scroll_b0c0n0",          {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_scroll_b0c0n0s0",        {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_scroll_b0c0s0",          {"mo_l_sm_ndw_blend_i0c0s0"}},
			{"mc_l_scroll_r0c0",            {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_scroll_r0c0d0",          {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_scroll_r0c0d0n0",        {"mo_l_sm_replace_i0c0n0d0"}},
			{"mc_l_scroll_r0c0d0n0s0",      {"mo_l_sm_replace_i0c0s0n0d0", "", "mo_l_sm_replace_i0c0s0n0d0p0"}},
			{"mc_l_scroll_r0c0d0s0",        {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_scroll_r0c0n0",          {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_scroll_r0c0n0s0",        {"mo_l_sm_replace_i0c0s0n0", "", "mo_l_sm_replace_i0c0s0n0p0"}},
			{"mc_l_scroll_r0c0s0",          {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_scroll_t0c0",            {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_scroll_t0c0d0",          {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_scroll_t0c0d0n0",        {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_scroll_t0c0d0n0s0",      {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_scroll_t0c0d0s0",        {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_scroll_t0c0n0",          {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_scroll_t0c0n0s0",        {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_scroll_t0c0s0",          {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_skin_r0c0",              {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_skin_r0c0d0",            {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_skin_r0c0d0n0",          {"mo_l_sm_replace_i0c0n0d0"}},
			{"mc_l_skin_r0c0d0n0s0",        {"mo_l_sm_replace_i0c0s0n0d0", "", "mo_l_sm_replace_i0c0s0n0d0p0"}},
			{"mc_l_skin_r0c0d0s0",          {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_skin_r0c0n0",            {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_skin_r0c0n0s0",          {"mo_l_sm_replace_i0c0s0n0", "", "mo_l_sm_replace_i0c0s0n0p0"}},
			{"mc_l_skin_r0c0s0",            {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_sm_b0c0",                {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_b0c0d0",              {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_b0c0d0n0",            {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_b0c0d0n0s0",          {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_sm_b0c0d0s0",            {"mo_l_sm_ndw_blend_i0c0s0"}},
			{"mc_l_sm_b0c0n0",              {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_b0c0n0s0",            {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_sm_b0c0n0s0p0",          {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_sm_b0c0p0",              {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_b0c0s0",              {"mo_l_sm_ndw_blend_i0c0s0"}},
			{"mc_l_sm_flag_t0c0",           {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_flag_t0c0n0",         {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_flag_t0c0n0s0",       {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_sm_flag_t0c0s0",         {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_sm_r0c0",                {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_r0c0d0",              {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_r0c0d0n0",            {"mo_l_sm_replace_i0c0n0d0"}},
			{"mc_l_sm_r0c0d0n0s0",          {"mo_l_sm_replace_i0c0s0n0d0", "", "mo_l_sm_replace_i0c0s0n0d0p0"}},
			{"mc_l_sm_r0c0d0s0",            {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_sm_r0c0n0",              {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_r0c0n0s0",            {"mo_l_sm_replace_i0c0s0n0", "", "mo_l_sm_replace_i0c0s0n0p0"}},
			{"mc_l_sm_r0c0n0s0p0",          {"mo_l_sm_replace_i0c0s0n0", "", "mo_l_sm_replace_i0c0s0n0p0"}},
			{"mc_l_sm_r0c0s0",              {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_sm_r0c0s0p0",            {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_sm_scroll_b0c0",         {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_scroll_b0c0d0",       {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_scroll_b0c0d0n0",     {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_scroll_b0c0d0n0s0",   {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_sm_scroll_b0c0d0s0",     {"mo_l_sm_ndw_blend_i0c0s0"}},
			{"mc_l_sm_scroll_b0c0n0",       {"mo_l_sm_ndw_blend_i0c0s0n0"}},
			{"mc_l_sm_scroll_b0c0n0s0",     {"mo_l_sm_ndw_blend_i0c0s0n0", "", "", "mo_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"mc_l_sm_scroll_b0c0s0",       {"mo_l_sm_ndw_blend_i0c0s0"}},
			{"mc_l_sm_scroll_r0c0",         {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_scroll_r0c0d0",       {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_scroll_r0c0d0n0",     {"mo_l_sm_replace_i0c0n0d0"}},
			{"mc_l_sm_scroll_r0c0d0n0s0",   {"mo_l_sm_replace_i0c0s0n0d0", "", "mo_l_sm_replace_i0c0s0n0d0p0"}},
			{"mc_l_sm_scroll_r0c0d0s0",     {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_sm_scroll_r0c0n0",       {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_scroll_r0c0n0s0",     {"mo_l_sm_replace_i0c0s0n0", "", "mo_l_sm_replace_i0c0s0n0p0"}},
			{"mc_l_sm_scroll_r0c0s0",       {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_sm_scroll_t0c0",         {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_scroll_t0c0d0",       {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_scroll_t0c0d0n0",     {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_scroll_t0c0d0n0s0",   {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_sm_scroll_t0c0d0s0",     {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_sm_scroll_t0c0n0",       {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_scroll_t0c0n0s0",     {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_sm_scroll_t0c0s0",       {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_sm_skin_r0c0",           {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_skin_r0c0d0",         {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_skin_r0c0d0n0",       {"mo_l_sm_replace_i0c0n0d0"}},
			{"mc_l_sm_skin_r0c0d0n0s0",     {"mo_l_sm_replace_i0c0s0n0d0", "", "mo_l_sm_replace_i0c0s0n0d0p0"}},
			{"mc_l_sm_skin_r0c0d0s0",       {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_sm_skin_r0c0n0",         {"mo_l_sm_replace_i0c0s0n0"}},
			{"mc_l_sm_skin_r0c0n0s0",       {"mo_l_sm_replace_i0c0s0n0", "", "mo_l_sm_replace_i0c0s0n0p0"}},
			{"mc_l_sm_skin_r0c0s0",         {"mo_l_sm_replace_i0c0s0"}},
			{"mc_l_sm_t0c0",                {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_t0c0d0",              {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_t0c0d0n0",            {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_t0c0d0n0s0",          {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_sm_t0c0d0s0",            {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_sm_t0c0n0",              {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_sm_t0c0n0s0",            {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_sm_t0c0s0",              {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_t0c0",                   {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_t0c0d0",                 {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_t0c0d0n0",               {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_t0c0d0n0s0",             {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_t0c0d0s0",               {"mo_l_sm_atest_i0c0s0"}},
			{"mc_l_t0c0n0",                 {"mo_l_sm_atest_i0c0s0n0"}},
			{"mc_l_t0c0n0s0",               {"mo_l_sm_atest_i0c0s0n0", "", "", "mo_l_sm_atest_i0c0s0n0pa0"}},
			{"mc_l_t0c0s0",                 {"mo_l_sm_atest_i0c0s0"}},
			{"wc_l_b0c0",                   {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_b0c0d0",                 {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_b0c0d0n0",               {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_b0c0d0n0s0",             {"wc_l_sm_ndw_blend_i0c0s0n0", "", "", "wc_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"wc_l_b0c0d0s0",               {"wc_l_sm_ndw_blend_i0c0s0"}},
			{"wc_l_b0c0n0",                 {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_b0c0n0s0",               {"wc_l_sm_ndw_blend_i0c0s0n0", "", "", "wc_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"wc_l_b0c0s0",                 {"wc_l_sm_ndw_blend_i0c0s0"}},
			{"wc_l_flag_t0c0",              {"wc_l_sm_atest_i0c0"}},
			{"wc_l_flag_t0c0n0",            {"wc_l_sm_atest_i0c0"}},
			{"wc_l_flag_t0c0n0s0",          {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_flag_t0c0s0",            {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_r0c0",                   {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_r0c0d0",                 {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_r0c0d0n0",               {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_r0c0d0n0s0",             {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_r0c0d0s0",               {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_r0c0n0",                 {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_r0c0n0s0",               {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_r0c0s0",                 {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_scroll_b0c0",            {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_scroll_b0c0d0",          {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_scroll_b0c0d0n0",        {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_scroll_b0c0d0n0s0",      {"wc_l_sm_ndw_blend_i0c0s0n0", "", "", "wc_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"wc_l_scroll_b0c0d0s0",        {"wc_l_sm_ndw_blend_i0c0s0"}},
			{"wc_l_scroll_b0c0n0",          {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_scroll_b0c0n0s0",        {"wc_l_sm_ndw_blend_i0c0s0n0", "", "", "wc_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"wc_l_scroll_b0c0s0",          {"wc_l_sm_ndw_blend_i0c0s0"}},
			{"wc_l_scroll_r0c0",            {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_scroll_r0c0d0",          {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_scroll_r0c0d0n0",        {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_scroll_r0c0d0n0s0",      {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_scroll_r0c0d0s0",        {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_scroll_r0c0n0",          {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_scroll_r0c0n0s0",        {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_scroll_r0c0s0",          {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_scroll_t0c0",            {"wc_l_sm_atest_i0c0"}},
			{"wc_l_scroll_t0c0d0",          {"wc_l_sm_atest_i0c0"}},
			{"wc_l_scroll_t0c0d0n0",        {"wc_l_sm_atest_i0c0"}},
			{"wc_l_scroll_t0c0d0n0s0",      {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_scroll_t0c0d0s0",        {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_scroll_t0c0n0",          {"wc_l_sm_atest_i0c0"}},
			{"wc_l_scroll_t0c0n0s0",        {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_scroll_t0c0s0",          {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_skin_r0c0",              {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_skin_r0c0d0",            {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_skin_r0c0d0n0",          {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_skin_r0c0d0n0s0",        {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_skin_r0c0d0s0",          {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_skin_r0c0n0",            {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_skin_r0c0n0s0",          {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_skin_r0c0s0",            {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_sm_b0c0",                {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_sm_b0c0d0",              {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_sm_b0c0d0n0",            {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_sm_b0c0d0n0s0",          {"wc_l_sm_ndw_blend_i0c0s0n0", "", "", "wc_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"wc_l_sm_b0c0d0s0",            {"wc_l_sm_ndw_blend_i0c0s0"}},
			{"wc_l_sm_b0c0n0",              {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_sm_b0c0n0s0",            {"wc_l_sm_ndw_blend_i0c0s0n0", "", "", "wc_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"wc_l_sm_b0c0s0",              {"wc_l_sm_ndw_blend_i0c0s0"}},
			{"wc_l_sm_flag_t0c0",           {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_flag_t0c0n0",         {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_flag_t0c0n0s0",       {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_flag_t0c0s0",         {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_r0c0",                {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_r0c0d0",              {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_r0c0d0n0",            {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_r0c0d0n0s0",          {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_sm_r0c0d0s0",            {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_sm_r0c0n0",              {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_r0c0n0s0",            {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_sm_r0c0s0",              {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_sm_scroll_b0c0",         {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_sm_scroll_b0c0d0",       {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_sm_scroll_b0c0d0n0",     {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_sm_scroll_b0c0d0n0s0",   {"wc_l_sm_ndw_blend_i0c0s0n0", "", "", "wc_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"wc_l_sm_scroll_b0c0d0s0",     {"wc_l_sm_ndw_blend_i0c0s0"}},
			{"wc_l_sm_scroll_b0c0n0",       {"wc_l_sm_ndw_blend_i0c0s0n0"}},
			{"wc_l_sm_scroll_b0c0n0s0",     {"wc_l_sm_ndw_blend_i0c0s0n0", "", "", "wc_l_sm_ndw_blend_i0c0s0n0pa0"}},
			{"wc_l_sm_scroll_b0c0s0",       {"wc_l_sm_ndw_blend_i0c0s0"}},
			{"wc_l_sm_scroll_r0c0",         {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_scroll_r0c0d0",       {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_scroll_r0c0d0n0",     {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_scroll_r0c0d0n0s0",   {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_sm_scroll_r0c0d0s0",     {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_sm_scroll_r0c0n0",       {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_scroll_r0c0n0s0",     {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_sm_scroll_r0c0s0",       {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_sm_scroll_t0c0",         {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_scroll_t0c0d0",       {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_scroll_t0c0d0n0",     {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_scroll_t0c0d0n0s0",   {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_scroll_t0c0d0s0",     {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_scroll_t0c0n0",       {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_scroll_t0c0n0s0",     {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_scroll_t0c0s0",       {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_skin_r0c0",           {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_skin_r0c0d0",         {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_skin_r0c0d0n0",       {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_skin_r0c0d0n0s0",     {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_sm_skin_r0c0d0s0",       {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_sm_skin_r0c0n0",         {"wc_l_sm_replace_i0c0s0n0"}},
			{"wc_l_sm_skin_r0c0n0s0",       {"wc_l_sm_replace_i0c0s0n0", "", "wc_l_sm_replace_i0c0s0n0p0"}},
			{"wc_l_sm_skin_r0c0s0",         {"wc_l_sm_replace_i0c0s0"}},
			{"wc_l_sm_t0c0",                {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_t0c0d0",              {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_t0c0d0n0",            {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_t0c0d0n0s0",          {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_t0c0d0s0",            {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_t0c0n0",              {"wc_l_sm_atest_i0c0"}},
			{"wc_l_sm_t0c0n0s0",            {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_sm_t0c0s0",              {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_t0c0",                   {"wc_l_sm_atest_i0c0"}},
			{"wc_l_t0c0d0",                 {"wc_l_sm_atest_i0c0"}},
			{"wc_l_t0c0d0n0",               {"wc_l_sm_atest_i0c0"}},
			{"wc_l_t0c0d0n0s0",             {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_t0c0d0s0",               {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_t0c0n0",                 {"wc_l_sm_atest_i0c0"}},
			{"wc_l_t0c0n0s0",               {"wc_l_sm_atest_i0c0s0"}},
			{"wc_l_t0c0s0",                 {"wc_l_sm_atest_i0c0s0"}},

			{"mc_ambient_r0c0",             {"mo_l_sm_replace_i0c0"}},
			{"mc_ambient_t0c0",             {"mo_l_sm_atest_i0c0"}},
			{"wc_ambient_r0c0",             {"wc_l_sm_replace_i0c0"}},
			{"wc_ambient_t0c0",             {"wc_l_sm_atest_i0c0"}},
			// ---- hand-written --------------------------------------------------------------------
			//
			// Names with no [rbt]0 blend letter, so the generator cannot derive them. These must survive
			// a regeneration.
			{"mc_effect_falloff_add_nofog",				make_techset_map("eq_effect_falloff_add_lin_nofog_ndw_nocast")},
			{"mc_effect_zfeather_falloff_add_nofog",	make_techset_map("eq_effect_zfeather_falloff_add_lin_nofog_ndw_nocast")},
			{"mc_effect_zfeather_falloff_add_nofog_eyeoffset",	make_techset_map("eq_effect_zfeather_falloff_add_lin_nofog_eyeoffset_ndw_nocast")},
			{"mc_effect_zfeather_falloff_add_lin_nofog_eyeoffset", make_techset_map("eq_effect_zfeather_falloff_add_lin_nofog_eyeoffset_ndw_nocast")},
			
			{"mc_unlit",								make_techset_map("mo_unlit_replace_lin", "mo_unlit_replace_lin_ct")},
			{"mc_unlit_replace",						make_techset_map("mo_unlit_replace_lin", "mo_unlit_replace_lin_ct")},
			{"mc_unlit_replace_lin",                 make_techset_map("mo_unlit_replace_lin", "mo_unlit_replace_lin_ct")},
			{"mc_unlit_replace_lin_nocast",          make_techset_map("mo_unlit_replace_lin_nocast")},
			{"mc_unlit_add",						make_techset_map("mo_unlit_add_lin_ndw", "mo_unlit_add_lin_ct_ndw")},
			{"mc_unlit_alphatest",						make_techset_map("mo_unlit_atest_lin_ct", "mo_unlit_atest_lin_ct")},
			{"mc_unlit_blend_lin",                   make_techset_map("mo_unlit_blend_lin_ndw")},
			// IW7 has no screen blend counterpart in the shipped techset list.
			{"mc_unlit_screen_lin_ua",              make_techset_map("mo_unlit_blend_lin_ndw_ua")},
			{"mc_threed_cinematic",                 make_techset_map("mo_threed_cinematic|_evc")},
			{"mc_ambient_t0c0_nocast",              make_techset_map("mo_l_sm_atest_i0c0s0n0_nocast")},
			{"m_l_sm_b0c0s0_sat",                   make_techset_map("m_l_sm_ndw_blend_i0c0s0")},
			{"m_l_sm_b0c0q0n0s0_sat",               make_techset_map("m_l_sm_ndw_blend_i0c0s0n0")},
			
			{"wc_unlit",							make_techset_map("wc_unlit_replace_lin", "wc_unlit_replace_lin_ct")},
			{"wc_unlit_add",							make_techset_map("wc_unlit_add_lin_ndw", "wc_unlit_add_lin_ct_ndw")},
			{"wc_unlit_multiply",						make_techset_map("wc_unlit_multiply_lin_ndw")},
			{"wc_unlit_falloff_add",					make_techset_map("wc_unlit_falloff_add_lin_ndw", "wc_unlit_falloff_add_lin_ct_ndw")},
			{"wc_unlit_add_lin",                    make_techset_map("wc_unlit_add_lin_ndw")},
			{"wc_unlit_add_lin_ua",                 make_techset_map("wc_unlit_add_lin_ndw_ua")},
			{"wc_unlit_blend_lin_ua",               make_techset_map("wc_unlit_blend_lin_ndw_ua")},
			{"wc_unlit_blend_lin_custom_objective", make_techset_map("wc_unlit_blend_lin_ndw_custom_objective")},
			// These fall back to stock world blend/replace techsets; IW7 has no matching
			// distfalloff replace, vertex-colour no-cast/UA replace, or ocean shader.
			{"wc_unlit_distfalloff_replace",        make_techset_map("wc_unlit_blend_lin_ndw")},
			{"wc_unlit_multiply_lin",               make_techset_map("wc_unlit_multiply_lin_ndw")},
			{"wc_unlit_replace_lin",                make_techset_map("wc_unlit_replace_lin", "wc_unlit_replace_lin_ct")},
			{"wc_unlit_replace_lin_nocast",         make_techset_map("wc_unlit_replace_lin", "wc_unlit_replace_lin_ct_nocast")},
			{"wc_unlit_replace_lin_ua",             make_techset_map("wc_unlit_replace_lin_ct_ua")},
			//{"wc_ocean_sm_foam_detail_flatn",       make_techset_map("wc_unlit_blend_lin_ndw")},
			//{"wc_ocean_sm_displace_foam_detail_flatn", make_techset_map("wc_unlit_blend_lin_ndw")},
			{"wc_distortion_scale",                 make_techset_map("wc_distortion_scale")},
			{"wc_distortion_scale_ua",              make_techset_map("wc_distortion_scale_ua")},
			{"wc_distortion_scale_zfeather",        make_techset_map("wc_distortion_scale")},
			{"wc_distortion_scale_ua_zfeather",     make_techset_map("wc_distortion_scale_ua")},
			{"wc_l_sm_t0c0_nocast",                 make_techset_map("wc_l_sm_atest_i0c0_nocast")},
			{"wc_l_t0c0_nocast",                    make_techset_map("wc_l_sm_atest_i0c0_nocast")},
			{"tools_b0c0",                          make_techset_map("tools_b0c0")},

			{"mc_shadowcaster",							make_techset_map("m_shadowcaster")},
			{"mc_shadowcaster_atest",					make_techset_map("m_shadowcaster")},
			{"wc_shadowcaster",							make_techset_map("w_shadowcaster")},

			{"distortion_scale_zfeather",				make_techset_map("eq_distortion_scale_zfeather")},

			{"wc_sky",									make_techset_map("w_sky")},

			{"2d",										make_techset_map("2d", "2d|_ct")},

			{"effect",									make_techset_map("eq_effect_blend_lin_ndw_nocast")},
			{"effect_nofog",							make_techset_map("eq_effect_blend_lin_nofog_ndw_nocast")},
			{"effect_zfeather_add",						make_techset_map("eq_effect_zfeather_add_lin_ct_ndw_nocast")},
			{"effect_zfeather_add_nofog_eyeoffset",		make_techset_map("eq_effect_zfeather_add_lin_nofog_eyeoffset_ndw_nocast")},
			{"effect_zfeather_add_nofog",				make_techset_map("eq_effect_zfeather_add_lin_nofog_ndw_nocast")},

			{"distortion_scale",						make_techset_map("eq_distortion_scale")},
			{"distortion_scale_zfeather",				make_techset_map("eq_distortion_scale_zfeather")},
		};

		std::unordered_map<std::string, techset_map_s> mapped_techsets_effect_vertlit =
		{
			{"effect",									make_techset_map("ev_effect_blend_lin_ct_ndw_nocast")},
		};

		enum MaterialType : std::uint8_t
		{
			MTL_TYPE_DEFAULT = 0x0, // ""
			MTL_TYPE_MODEL = 1, // "m"
			MLT_TYPE_MODEL_UNK2 = 2,
			MTL_TYPE_MODEL_UNK3 = 3,
			MTL_TYPE_MODEL_UNK4 = 4,
			MTL_TYPE_MODEL_UNK5 = 5,
			MTL_TYPE_MODEL_UNK6 = 6,
			MTL_TYPE_MODEL_UNK7 = 7,
			MTL_TYPE_MODEL_UNK8 = 8,
			MTL_TYPE_MODEL_UNK9 = 9,
			MTL_TYPE_MODEL_UNK10 = 10,
			MTL_TYPE_MODEL_UNK11 = 11,
			MTL_TYPE_MODEL_UNK12 = 12,
			MTL_TYPE_MODEL_UNK13 = 13,
			MTL_TYPE_MODEL_UNK14 = 14,
			MTL_TYPE_MODEL_UNK15 = 15,
			MTL_TYPE_MODEL_LMAP = 16, // "ml"
			MTL_TYPE_MODEL_LMAP_VERTCOL = 17, // "mlc"
			MTL_TYPE_MODEL_UNK18 = 18,
			MTL_TYPE_MODEL_UNK19 = 19,
			MTL_TYPE_MODEL_UNK20 = 20,
			MTL_TYPE_MODEL_UNK21 = 21,
			MTL_TYPE_MODEL_IMPACT = 22, // "mim"
			MTL_TYPE_MODEL_SELFVIS = 23, // "mo"
			MTL_TYPE_MODEL_VERTCOL_SELFVIS = 24, // "mco"
			MTL_TYPE_MODEL_UNK25 = 25, // "mvo"
			MTL_TYPE_MODEL_UNK26 = 26, // "mvco"
			MTL_TYPE_MODEL_UNK27 = 27,
			MTL_TYPE_MODEL_SECONDUV_SELFVIS = 28, // "m2o"
			MTL_TYPE_MODEL_SECONDUV_VERTCOL_SELFVIS = 29, // "m2co"
			MTL_TYPE_MODEL_UNK30 = 30, // "mop"
			MTL_TYPE_MODEL_UNK31 = 31, // "m2op"
			MTL_TYPE_MODEL_UNK32 = 32,
			MTL_TYPE_MODEL_UNK33 = 33,
			MTL_TYPE_MODEL_UNK34 = 34,
			MTL_TYPE_MODEL_UNK35 = 35,
			MTL_TYPE_MODEL_UNK36 = 36,
			MTL_TYPE_MODEL_UNK37 = 37, // "mopw"
			MTL_TYPE_MODEL_UNK38 = 38, // "m2opw"
			MTL_TYPE_MODEL_UNK39 = 39, // "m2copw"
			MTL_TYPE_MODEL_UNK40 = 40, // "mcopw"
			MTL_TYPE_MODEL_UNK41 = 41, // "mvopw"
			MTL_TYPE_MODEL_UNK42 = 42,
			MTL_TYPE_MODEL_UNK43 = 43,
			MTL_TYPE_MODEL_SUBDIV = 44, // "ms"
			MTL_TYPE_MODEL_UNK45 = 45,
			MTL_TYPE_MODEL_UNK46 = 46,
			MTL_TYPE_MODEL_UNK47 = 47, // "msa"
			MTL_TYPE_MODEL_UNK48 = 48,
			MTL_TYPE_MODEL_UNK49 = 49,
			MTL_TYPE_MODEL_UNK50 = 50,
			MTL_TYPE_MODEL_UNK51 = 51,
			MTL_TYPE_MODEL_UNK52 = 52,
			MTL_TYPE_MODEL_SUBDIV_VERTCOL_SELFVIS = 53, // "msco"
			MTL_TYPE_MODEL_UNK54 = 54, // "mszo"
			MTL_TYPE_MODEL_UNK55 = 55, // "msvo"
			MTL_TYPE_MODEL_UNK56 = 56, // "msvco"
			MTL_TYPE_MODEL_SUBDIV_SELFVIS = 57, // "mso"
			MTL_TYPE_MODEL_UNK58 = 58, // "msop"
			MTL_TYPE_MODEL_UNK59 = 59,
			MTL_TYPE_MODEL_UNK60 = 60,
			MTL_TYPE_MODEL_UNK61 = 61,
			MTL_TYPE_MODEL_UNK62 = 62,
			MTL_TYPE_MODEL_UNK63 = 63, // "msopw"
			MTL_TYPE_MODEL_UNK64 = 64, // "mscopw"
			MTL_TYPE_MODEL_UNK65 = 65,
			MTL_TYPE_MODEL_UNK66 = 66,
			MTL_TYPE_MODEL_UNK67 = 67,
			MTL_TYPE_WORLD = 68, // "w"
			MTL_TYPE_WORLD_VERTCOL = 69, // "wc"
			MTL_TYPE_WORLD_IMPACT = 70, // "wim"
			MTL_TYPE_EFFECT_LMAP = 71, // "el"
			MTL_TYPE_EFFECT_VERTLIT = 72, // "ev"
			MTL_TYPE_EFFECT_QUAD = 73, // "eq"
		};

		std::string prefixes[] =
		{
			"w",
			"wc",
			"mo",
			"ev",
			"eq",
			// particle_cloud_* techsets carry no prefix of their own, stock materials on them are el/ with type 71
			"particle",
		};

		std::uint8_t prefixes_types[] =
		{
			MTL_TYPE_WORLD,
			MTL_TYPE_WORLD_VERTCOL,
			MTL_TYPE_MODEL_SELFVIS,
			MTL_TYPE_EFFECT_VERTLIT,
			MTL_TYPE_EFFECT_QUAD,
			MTL_TYPE_EFFECT_LMAP,
		};

		std::string material_prefix_for(const std::string& prefix)
		{
			return prefix == "particle" ? "el" : prefix;
		}

		std::string canonical_iw5_techset(std::string techset)
		{
			// Prefer exact entries. IW5's saturation, parallax, heat, detail-normal,
			// dust/melt and growing-ice variants have no equivalent in the stock IW7
			// techsets used here, so reuse the mapped base technique and its slot set.
			for (int i = 0; i < 8; i++)
			{
				if (mapped_techsets.contains(techset) || mapped_techsets_effect_vertlit.contains(techset))
				{
					return techset;
				}
				if (techset.ends_with("_sat"))
				{
					techset.erase(techset.size() - 4);
				}
				else if (techset.ends_with("_nocast"))
				{
					techset.erase(techset.size() - 7);
				}
				else if (techset.ends_with("_custom_growing_ice_cracks"))
				{
					techset.erase(techset.size() - 26);
				}
				else if (techset.ends_with("p0") && techset.find("_l_sm_") != std::string::npos)
				{
					techset.erase(techset.size() - 2);
				}
				else if (const auto heat = techset.find("_l_sm_heat_"); heat != std::string::npos)
				{
					techset.replace(heat, 11, "_l_sm_");
				}
				else if (const auto detail_normal = techset.find("q0");
					detail_normal != std::string::npos && techset.find("_l_sm_") != std::string::npos)
				{
					techset.erase(detail_normal, 2);
				}
				else if (const auto du_dm = techset.find("_l_sm_du_dm_"); du_dm != std::string::npos)
				{
					techset.replace(du_dm, 12, "_l_sm_");
				}
				else if (techset.starts_with("wc_l_sm_ua_"))
				{
					techset.erase(7, 3);
				}
				else
				{
					break;
				}
			}
			return techset;
		}

		// The p0 counterpart of a techset, or empty if it has none. Keyed on the IW5 name,
		// like the table itself, so several IW5 techsets collapsing onto one IW7 target each
		// carry their own answer. color_tint is deliberately not consulted: no ct material
		// has a packed target yet, and silently dropping the tint would be worse than
		// staying unpacked.
		std::string get_packed_techset(const std::string& techset, const bool effect_vertlit)
		{
			const auto mapped_name = canonical_iw5_techset(techset);

			const auto& table = effect_vertlit ? mapped_techsets_effect_vertlit : mapped_techsets;
			const auto it = table.find(mapped_name);
			if (it != table.end() && !it->second.techset[techset_map_type_e::packed].empty())
			{
				return it->second.techset[techset_map_type_e::packed];
			}

			// an FX-referenced material falls back to the regular table, same as above
			if (effect_vertlit)
			{
				const auto regular = mapped_techsets.find(mapped_name);
				if (regular != mapped_techsets.end())
				{
					return regular->second.techset[techset_map_type_e::packed];
				}
			}

			return {};
		}

		// The pa0 counterpart, on the same terms as get_packed_techset above.
		std::string get_packed_alpha_techset(const std::string& techset, const bool effect_vertlit)
		{
			const auto mapped_name = canonical_iw5_techset(techset);

			const auto& table = effect_vertlit ? mapped_techsets_effect_vertlit : mapped_techsets;
			const auto it = table.find(mapped_name);
			if (it != table.end() && !it->second.techset[techset_map_type_e::packed_alpha].empty())
			{
				return it->second.techset[techset_map_type_e::packed_alpha];
			}

			if (effect_vertlit)
			{
				const auto regular = mapped_techsets.find(mapped_name);
				if (regular != mapped_techsets.end())
				{
					return regular->second.techset[techset_map_type_e::packed_alpha];
				}
			}

			return {};
		}

		// IW3/IW4/IW5 effect techsets are named from a fixed set of features
		// (effect[_zfeather][_falloff|_distfalloff][_outdoor][_add|_blend|_multiply][_nofog][_eyeoffset][_spot...]),
		// and so are IW7's (eq_effect[_zfeather][_outdoor]_<blend>_lin[_ct][_nofog][_eyeoffset]_ndw_nocast).
		// The table above only names five of them, so everything else (effect_add, effect_zfeather,
		// effect_blend, ...) fell through to "2d", which doesn't draw as a particle. Build the IW7 name from the
		// features and only accept techsets that stock materials actually ship on; features IW7 has no match
		// for are dropped one at a time. Falloff is left out on purpose: those techsets take falloff
		// parameters the converter doesn't write.
		const std::unordered_set<std::string> stock_effect_techsets =
		{
			"eq_effect_add_lin_ct_ndw_nocast",
			"eq_effect_add_lin_ct_nofog_ndw_nocast",
			"eq_effect_add_lin_ndw_nocast",
			"eq_effect_add_lin_nofog_ndw_nocast",
			"eq_effect_blend_lin_ct_ndw_nocast",
			"eq_effect_blend_lin_ndw_nocast",
			"eq_effect_blend_lin_nofog_ndw_nocast",
			"eq_effect_zfeather_add_lin_ct_eyeoffset_ndw_nocast",
			"eq_effect_zfeather_add_lin_ct_ndw_nocast",
			"eq_effect_zfeather_add_lin_ct_nofog_eyeoffset_ndw_nocast",
			"eq_effect_zfeather_add_lin_ct_nofog_ndw_nocast",
			"eq_effect_zfeather_add_lin_eyeoffset_ndw_nocast",
			"eq_effect_zfeather_add_lin_ndw_nocast",
			"eq_effect_zfeather_add_lin_nofog_eyeoffset_ndw_nocast",
			"eq_effect_zfeather_add_lin_nofog_ndw_nocast",
			"eq_effect_zfeather_blend_lin_ct_ndw_nocast",
			"eq_effect_zfeather_blend_lin_ct_nofog_ndw_nocast",
			"eq_effect_zfeather_blend_lin_eyeoffset_ndw_nocast",
			"eq_effect_zfeather_blend_lin_ndw_nocast",
			"eq_effect_zfeather_blend_lin_nofog_eyeoffset_ndw_nocast",
			"eq_effect_zfeather_blend_lin_nofog_ndw_nocast",
			"eq_effect_zfeather_outdoor_blend_lin_ndw_nocast",
			"ev_effect_add_lin_ct_ndw_nocast",
			"ev_effect_add_lin_nofog_ndw_nocast",
			"ev_effect_blend_lin_ct_ndw_nocast",
			"ev_effect_blend_lin_ndw_nocast",
			"ev_effect_blend_lin_nofog_ndw_nocast",
			"ev_effect_zfeather_add_lin_ndw_nocast",
			"ev_effect_zfeather_blend_lin_ct_ndw_nocast",
			"ev_effect_zfeather_blend_lin_ndw_nocast",
			"particle_cloud_add_ct_lin",
			"particle_cloud_add_lin",
			"particle_cloud_blend_ct_lin",
			"particle_cloud_blend_lin",
			"particle_cloud_outdoor_add_lin",
			"particle_cloud_outdoor_blend_lin",
			"particle_cloud_spark_add_ct_lin",
			"particle_cloud_spark_add_lin",
			"particle_cloud_spark_blend_ct_lin",
		};

		std::string map_effect_techset_by_features(const std::string& techset, const bool effect_vertlit, const bool color_tint)
		{
			std::vector<std::string> parts;
			for (std::size_t start = 0, end; start <= techset.size(); start = end + 1)
			{
				end = techset.find('_', start);
				if (end == std::string::npos) end = techset.size();
				parts.emplace_back(techset.substr(start, end - start));
			}

			const auto has = [&](const char* part) { return std::find(parts.begin(), parts.end(), part) != parts.end(); };

			const bool is_cloud = techset.starts_with("particle_cloud");
			if (!is_cloud && !techset.starts_with("effect"))
			{
				return {};
			}

			// shadow-map spot variants only differ in lighting, which IW7 handles itself
			const bool add = has("add");
			const bool nofog = has("nofog");
			const bool eyeoffset = has("eyeoffset");
			const bool outdoor = has("outdoor");

			if (is_cloud)
			{
				const bool spark = has("spark") || has("sparkf");
				for (const auto tint : { color_tint, false })
				{
					for (const auto keep_variant : { true, false })
					{
						std::string name = "particle_cloud";
						if (keep_variant && spark) name += "_spark";
						else if (keep_variant && outdoor) name += "_outdoor";
						name += (add || spark) ? "_add" : "_blend";
						name += tint ? "_ct_lin" : "_lin";
						if (stock_effect_techsets.contains(name)) return name;
					}
				}
				return {};
			}

			// multiply and (dist)falloff have no counterpart the converter can feed, the blend mode is kept
			const bool zfeather = has("zfeather");
			// "effect" and IW5's "effect_blend" are both blended quads
			const std::string blend = add ? "add" : "blend";

			const char* prefix = effect_vertlit ? "ev" : "eq";
			// drop features in the order they matter least
			for (const auto tint : { color_tint, false })
			{
				for (auto drop = 0; drop < 5; drop++)
				{
					const bool use_outdoor = outdoor && drop < 1;
					const bool use_eyeoffset = eyeoffset && drop < 2;
					const bool use_nofog = nofog && drop < 3;
					const bool use_zfeather = zfeather && drop < 4;

					std::string name = std::string(prefix) + "_effect";
					if (use_zfeather) name += "_zfeather";
					if (use_outdoor) name += "_outdoor";
					name += "_" + blend + "_lin";
					if (tint) name += "_ct";
					if (use_nofog) name += "_nofog";
					if (use_eyeoffset) name += "_eyeoffset";
					name += "_ndw_nocast";

					if (stock_effect_techsets.contains(name)) return name;
				}
			}

			// the vertlit table has few entries; a quad effect is still a valid material for a particle
			return effect_vertlit ? map_effect_techset_by_features(techset, false, color_tint) : std::string{};
		}

		std::string get_mapped_techset(const std::string& techset, const bool effect_vertlit, const bool color_tint)
		{
			const auto mapped_name = canonical_iw5_techset(techset);
			if (!effect_vertlit)
			{
				const auto it = mapped_techsets.find(mapped_name);
				if (it != mapped_techsets.end())
				{
					auto tech = it->second.techset[color_tint ? techset_map_type_e::color_tint : techset_map_type_e::regular];
					return tech.empty() ? it->second.techset[techset_map_type_e::regular] : tech;
				}
			}
			else
			{
				const auto it = mapped_techsets_effect_vertlit.find(mapped_name);
				if (it != mapped_techsets_effect_vertlit.end())
				{
					auto tech = it->second.techset[color_tint ? techset_map_type_e::color_tint : techset_map_type_e::regular];
					return tech.empty() ? it->second.techset[techset_map_type_e::regular] : tech;
				}

				// The vertlit table only covers techsets that are genuinely effect-vertlit.
				// Everything else reaching here is an ordinary material that an FX happens to
				// reference -- ParticleSystem re-dumps those with effect_vertlit set, after the
				// normal dump, so returning "2d" here overwrites a correctly mapped material
				// with the fallback. Fall through to the regular table instead.
				const auto regular = mapped_techsets.find(mapped_name);
				if (regular != mapped_techsets.end())
				{
					auto tech = regular->second.techset[color_tint ? techset_map_type_e::color_tint : techset_map_type_e::regular];
					return tech.empty() ? regular->second.techset[techset_map_type_e::regular] : tech;
				}
			}

			if (auto effect = map_effect_techset_by_features(techset, effect_vertlit, color_tint); !effect.empty())
			{
				return effect;
			}

			return "2d";
		}

		std::unordered_map<std::string, std::string> prefix_cache;

		std::string resolve_material_name(const std::string& name)
		{
			const auto renamed = prefix_cache.find(name);
			if (renamed != prefix_cache.end())
			{
				return renamed->second;
			}

			// Either the material keeps its own name - the common case, nothing to do - or it has
			// not been dumped yet, which would mean the fastfile referenced it before defining it.
			// There is no way to tell the two apart from here, and guessing would mean computing a
			// techset we do not have, so hand back the name and let the linker report the miss.
			return name;
		}

		std::string replace_material_prefix(const std::string& name, const std::string& techset, const bool effect_vertlit, const bool color_tint)
		{
			if (prefix_cache.contains(name))
			{
				return prefix_cache[name];
			}

			std::string new_tech = get_mapped_techset(techset, effect_vertlit, color_tint);

			for (const auto& prefix : prefixes)
			{
				if (new_tech.starts_with(prefix + "_"))
				{
					const auto slash_pos = name.find('/');
					const size_t replace_len = (slash_pos == std::string::npos) ? 0 : slash_pos + 1;
					const std::string replacement = material_prefix_for(prefix) + "/";

					std::string replaced = name;
					replaced.replace(0, replace_len, replacement);

					prefix_cache[name] = replaced;

					// The zone csv is written from the source game's asset name, and the line for
					// this material was emitted just before it reached the dumper. Record the new
					// name so the linker can substitute it when it flushes the csv at close.
					zonetool::filesystem::csv_register_rename("material", name, replaced);

					return replaced;
				}
			}

			return name;
		}

		std::uint8_t get_material_type_from_techset(std::string techset) // iw7_techset
		{
			if (!techset.empty())
			{
				for (auto prefix_idx = 0; prefix_idx < std::size(prefixes); prefix_idx++)
				{
					const auto prefix = prefixes[prefix_idx];
					const auto type = prefixes_types[prefix_idx];

					if (techset.starts_with(prefix + "_"))
					{
						return type;
					}
				}
			}

			return IW7::MTL_TYPE_DEFAULT;
		}

		IW7::TextureSemantic surf_flags_conversion_table[13]
		{
			IW7::TextureSemantic::TS_2D,
			IW7::TextureSemantic::TS_FUNCTION,
			IW7::TextureSemantic::TS_COLOR_MAP,
			IW7::TextureSemantic::TS_DETAIL_MAP,
			IW7::TextureSemantic::TS_UNUSED_4,
			IW7::TextureSemantic::TS_NORMAL_MAP,
			IW7::TextureSemantic::TS_UNUSED_6,
			IW7::TextureSemantic::TS_UNUSED_7,
			IW7::TextureSemantic::TS_SPECULAR_MAP,
			IW7::TextureSemantic::TS_UNUSED_4,
			IW7::TextureSemantic::TS_UNUSED_4,
			IW7::TextureSemantic::TS_UNUSED_4, // WATER_MAP
			IW7::TextureSemantic::TS_DISPLACEMENT_MAP,
		}; IW5::TextureSemantic;

		std::uint8_t convert_semantic(std::uint8_t from)
		{
			return surf_flags_conversion_table[from];
		}

		namespace
		{
			std::string get_IW7_techset(std::string name, std::string matname, bool* result, bool effect_vertlit = false, bool has_ct = false)
			{
				auto iw7_techset = get_mapped_techset(name, effect_vertlit, has_ct);

				*result = true;
				if (name != "2d" && iw7_techset == "2d")
				{
					ZONETOOL_ERROR("Could not find mapped IW7 techset for techset \"%s\" (material: %s)%s",
						name.data(),
						matname.data(),
						effect_vertlit ? " (EFFECT_VERTLIT)" : "");
					*result = false;
				}

				return iw7_techset;
			}

			std::unordered_map<std::uint8_t, std::uint8_t> mapped_sortkeys =
			{
				{0, 2},		// Opaque ambient (IW7 has no ambient bucket; 2 is where all 41038 stock opaque materials sit)
				{1, 2},		// Opaque
				{2, 3},     // Sky
				{3, 4},		// Skybox sun/moon
				{4, 5},		// Clouds  NOT SURE
				{5, 6},		// Horizon NOT SURE
				{6, 7},		// Decal bottom 1
				{7, 8},		// Decal bottom 2
				{8, 9},		// Decal bottom 3
				{9, 10},	// Decal static
				{10, 11},	// Decal mid 1
				{11, 12},	// Decal mid 2
				{12, 13},	// Decal mid 3
				{13, 14},	// Weapon Impact
				{14, 15},	// Decal top 1
				{15, 16},	// Decal top 2
				{16, 17},	// Decal top 3
				{17, 18},	// Multiplicative
				//{18, x},	// ?
				{19, 20},	// Underwater
				{20, 21},	// Transparent water
				//{21, x},	// ?
				//{22, x},	// ?
				//{23, x},	// ?
				{24, 25},   // Window inside
				{25, 26},   // Window outside
				{26, 27},	// Cloud 1
				{27, 28},	// Cloud 2
				{28, 29},	// Cloud 3
				{29, 30},	// Blend 1 / additive
				{30, 31},	// Blend 2
				{31, 32},	// Blend 3
				{32, 33},	// ?
				{33, 34},	// Corona
				{34, 2},	// Shadow Caster
				//{35, x},	// ?
				//{36, x},	// ?
				//{37, x},	// ?
				//{38, x},	// ?
				//{39, x},	// ?
				//{40, x},	// ?
				//{41, x},	// ?
				//{42, x},	// ?
				{43, 36},	// Effect Distortion
				{44, 36},	// Before effects bottom
				{45, 36},	// Before effects middle
				{46, 36},	// Before effects top
				{47, 30},	// cloud_glass, cloud_snowflake01 and sun ship on sort key 30 in IW7
				{48, 35},	// Effect auto sort
				{49, 35},	// After effects bottom
				{50, 35},	// After effects middle
				{51, 35},	// After effects top
				//{52, x},	// ?
				{53, 35},	// Viewmodel effect
				{54, 41},	// 2D
			};

			std::unordered_map<std::string, std::uint8_t> mapped_sortkeys_by_techset =
			{
				
			};

			std::uint8_t get_IW7_sortkey(std::uint8_t sortkey, std::string matname, std::string IW7_techset)
			{
				if (mapped_sortkeys_by_techset.find(IW7_techset) != mapped_sortkeys_by_techset.end())
				{
					return mapped_sortkeys_by_techset[IW7_techset];
				}

				if (mapped_sortkeys.contains(sortkey))
				{
					return mapped_sortkeys[sortkey];
				}

				ZONETOOL_ERROR("Could not find mapped IW7 sortkey for sortkey: %d (material: %s)", sortkey, matname.data());

				return sortkey;
			}

			std::unordered_map<std::uint8_t, std::uint8_t> mapped_camera_regions =
			{
				{IW5::CAMERA_REGION_LIT_OPAQUE, IW7::CAMERA_REGION_LIT_OPAQUE},
				{IW5::CAMERA_REGION_LIT_TRANS, IW7::CAMERA_REGION_LIT_TRANS},
				{IW5::CAMERA_REGION_EMISSIVE, IW7::CAMERA_REGION_NONE},
				{IW5::CAMERA_REGION_NONE, IW7::CAMERA_REGION_NONE},
			};

			std::unordered_map<std::string, std::uint8_t> mapped_camera_regions_by_techset =
			{
			};

			std::uint8_t get_IW7_camera_region(std::uint8_t camera_region, std::string matname, std::string IW7_techset)
			{
				if (mapped_camera_regions_by_techset.find(IW7_techset) != mapped_camera_regions_by_techset.end())
				{
					return mapped_camera_regions_by_techset[IW7_techset];
				}

				if (mapped_camera_regions.contains(camera_region))
				{
					return mapped_camera_regions[camera_region];
				}

				ZONETOOL_ERROR("Could not find mapped IW7 camera region for camera region: %d (material: %s)", camera_region, matname.data());

				return camera_region;
			}

			std::unordered_map<std::string, std::uint8_t> mapped_render_flags_by_techset =
			{
				{"2d", 0x1},
			};

			std::int32_t get_render_flags_by_techset(std::string IW7_techset)
			{
				std::int32_t flags = 0;

				if (mapped_render_flags_by_techset.find(IW7_techset) != mapped_render_flags_by_techset.end())
				{
					flags |= mapped_render_flags_by_techset[IW7_techset];
				}

				if (IW7_techset.starts_with("eq_") || IW7_techset.starts_with("ev_"))
				{
					flags |= 0x1;
				}

				return flags;
			}
		}
	}

	namespace IW5::IW7Dumper
	{
		std::string clean_name(const std::string& name)
		{
			auto new_name = name;

			for (auto i = 0u; i < name.size(); i++)
			{
				switch (new_name[i])
				{
				case '*':
					new_name[i] = '_';
					break;
				}
			}

			return new_name;
		}

		namespace
		{
			// ---- packed image names ----------------------------------------------------------
			//
			// Stock IW7 records a packed image's construction in its name:
			//
			//     <primary source>_<secondary token>_packed_<channels>
			//
			// The secondary token is spelled two different ways, and which one it is depends on
			// the target, not on the technique:
			//
			//   _packed_cs   the secondary is written out as a *name*. All 8381 stock _packed_cs
			//                names under zonetool_paths\techsets_*\materials end in the specular's
			//                name; not one ends in a hex token.
			//   everything   the secondary is an 8 lowercase hex digit hash - ng, nog, n, no, a,
			//   else         ar, at, r all use it, and 00000000 stands for "no secondary source"
			//                (2170 _packed_a, 3 _packed_r).
			//
			// The hash is djb2 seeded with zero, h = h * 33 + c, over the raw image name. Measured:
			// 3096 of the 3104 stock _packed_ng hashes resolve back to a real image name in the
			// corpus, and 737 of 775 reproduce exactly from the specular named in the same
			// material's _packed_cs -
			//
			//     camo_97_c_camo_97_sg_packed_cs        <-> camo_97_n_8d864148_packed_ng
			//     djb2_0("camo_97_sg")                   = 0x8d864148
			//
			//     iw7_drywall_painted_white_a_iw7_drywall_painted_white_c_sg_packed_cs
			//                                           <-> iw7_drywall_painted_white_n_cd821074_packed_ng
			//     djb2_0("iw7_drywall_painted_white_c_sg") = 0xcd821074
			//
			// The 38 that do not reproduce are materials whose _cs and _ng were built from
			// different source sets (a decal blended over a different base), not a second rule.
			// _packed_nog never reproduces because it hashes two secondaries, gloss and baked AO;
			// IW5 has no AO source so that target is never emitted here.
			// A texture slot is identified by the hash of its shader argument name, and the same
			// hash means the same slot in IW5 and IW7 - only the semantic the technique reads it
			// at changes. These are the four the converter handles.
			constexpr unsigned int slot_hash_colour = 2695565377;   // colorMap
			constexpr unsigned int slot_hash_normal = 1507003663;   // normalMap
			constexpr unsigned int slot_hash_spec   = 887934131;    // specularMap
			constexpr unsigned int slot_hash_detail = 3948059469;   // detailMap

			std::string packed_source_hash(const char* name)
			{
				if (!name || !*name)
				{
					return "00000000";
				}

				std::uint32_t hash = 0;
				for (const auto* c = name; *c; ++c)
				{
					hash = hash * 33 + static_cast<std::uint8_t>(*c);
				}

				return va("%08x", hash);
			}

			std::string packed_cs_name_for(const GfxImage* colour, const GfxImage* spec)
			{
				// Stock has no example of a _packed_cs built without a specular, so the absent
				// case is the one place this extrapolates: it borrows 00000000, which is the
				// token every other target uses for a missing secondary source.
				return va("%s_%s_packed_cs", colour->name,
					spec && spec->name && *spec->name ? spec->name : "00000000");
			}

			// <colour>_00000000_packed_a. The trailing token is the usual "no secondary source"
			// hash and it is not a guess here: all 2360 stock _packed_a names carry exactly
			// 00000000, because the map is one channel lifted straight out of the colour with
			// nothing blended into it. (_packed_ar does hash, since it folds in a roughness map;
			// IW5 has no such source, so that form is never emitted.)
			std::string packed_a_name_for(const GfxImage* colour)
			{
				return va("%s_%s_packed_a", colour->name, packed_source_hash(nullptr).data());
			}

			std::string packed_ng_name_for(const GfxImage* normal, const GfxImage* spec)
			{
				return va("%s_%s_packed_ng", normal->name,
					packed_source_hash(spec ? spec->name : nullptr).data());
			}

			// Building one of these is a full decode plus a BC7 encode of every mip, and stock
			// materials share them heavily - camo_97_c_camo_97_sg_packed_cs backs 905 of them.
			// Key the cache on the source pair so a repeat costs nothing and, in particular, does
			// not need the sources decoded again just to work out the name. An empty mapped value
			// records a pair that failed to build, so it is not retried either.
			//
			// The fastfile is part of the key because a cache hit skips the write, not just the
			// encode, and the write goes to dump\<fastfile>\ - which moves under us when several
			// zones are dumped in one run. Without it the second zone would reference a _packed_
			// image that only exists in the first zone's dump.
			std::unordered_map<std::string, std::string> packed_cs_cache;
			std::unordered_map<std::string, std::string> packed_ng_cache;
			std::unordered_map<std::string, std::string> packed_a_cache;

			std::string packed_cache_key(const GfxImage* primary, const GfxImage* secondary)
			{
				return zonetool::filesystem::get_fastfile() + "|" + primary->name + "|" +
					(secondary ? secondary->name : "");
			}

			// Decodes `spec` at most once per material, and only when something actually needs it.
			struct lazy_spec
			{
				GfxImage* source = nullptr;
				IW7Converter::decoded_image image;
				bool tried = false;
				bool ok = false;

				const IW7Converter::decoded_image* get()
				{
					if (!tried)
					{
						tried = true;
						ok = source && IW7Converter::decode_source(source, image);
					}

					return ok ? &image : nullptr;
				}
			};

			// The IW7 base layer, built regardless of which technique the material ends up on.
			// IW7 has no unpacked base layer to speak of - of 11,313 stock materials carrying real
			// textures only 247 use semantic 5 or 8 without 14/15, and every one is a tools_*
			// debug shader - so the pair is worth having whether or not the mapped techset has a
			// p0 form to bind it. See docs/iw7-packed-textures.md.
			std::string dump_packed_cs(GfxImage* colour, lazy_spec& spec)
			{
				if (!colour || !colour->name)
				{
					return {};
				}

				const auto key = packed_cache_key(colour, spec.source);
				const auto cached = packed_cs_cache.find(key);
				if (cached != packed_cs_cache.end())
				{
					return cached->second;
				}

				std::string name;

				allocator mem;
				IW7Converter::decoded_image colour_image;
				if (IW7Converter::decode_source(colour, colour_image))
				{
					// The name records what went into the image, so it can only claim a specular
					// that actually decoded - a spec that failed to load contributes no gloss.
					const auto* spec_image = spec.get();
					name = packed_cs_name_for(colour, spec_image ? spec.source : nullptr);

					// Fast dump keeps the name and skips the encode: the file is already in the
					// staging tree, and building it is the expensive half of a dump.
					if (fast_dump_enabled())
					{
					}
					else if (auto* built = IW7Converter::build_packed_cs(name.data(), colour_image,
						spec_image, mem))
					{
						IW7::IGfxImage::dump(built);
					}
					else
					{
						name.clear();
					}
				}

				packed_cs_cache[key] = name;
				return name;
			}

			// The opacity map a pa0 technique binds at semantic 16. Unlike the _cs/_ng pair this
			// is built only when something will reference it: it exists purely to serve a
			// technique that reads alpha, and every other material would carry a dead file.
			std::string dump_packed_a(GfxImage* colour)
			{
				if (!colour || !colour->name)
				{
					return {};
				}

				const auto key = packed_cache_key(colour, nullptr);
				const auto cached = packed_a_cache.find(key);
				if (cached != packed_a_cache.end())
				{
					return cached->second;
				}

				std::string name;

				allocator mem;
				IW7Converter::decoded_image colour_image;
				if (IW7Converter::decode_source(colour, colour_image))
				{
					name = packed_a_name_for(colour);

					// Fast dump keeps the name and skips the encode: the file is already in the
					// staging tree, and building it is the expensive half of a dump.
					if (fast_dump_enabled())
					{
					}
					else if (auto* built = IW7Converter::build_packed_a(name.data(), colour_image, mem))
					{
						IW7::IGfxImage::dump(built);
					}
					else
					{
						name.clear();
					}
				}

				packed_a_cache[key] = name;
				return name;
			}

			std::string dump_packed_ng(GfxImage* normal, lazy_spec& spec)
			{
				if (!normal || !normal->name)
				{
					return {};
				}

				const auto key = packed_cache_key(normal, spec.source);
				const auto cached = packed_ng_cache.find(key);
				if (cached != packed_ng_cache.end())
				{
					return cached->second;
				}

				std::string name;

				allocator mem;
				IW7Converter::decoded_image normal_image;
				if (IW7Converter::decode_source(normal, normal_image))
				{
					const auto* spec_image = spec.get();
					name = packed_ng_name_for(normal, spec_image ? spec.source : nullptr);

					// Fast dump keeps the name and skips the encode: the file is already in the
					// staging tree, and building it is the expensive half of a dump.
					if (fast_dump_enabled())
					{
					}
					else if (auto* built = IW7Converter::build_packed_ng(name.data(), normal_image,
						spec_image, mem))
					{
						IW7::IGfxImage::dump(built);
					}
					else
					{
						name.clear();
					}
				}

				packed_ng_cache[key] = name;
				return name;
			}

			// ---- the unpacked counterparts ---------------------------------------------------
			//
			// Not everything IW7 loads is packed. Semantic 8 is the specular slot a non-p0
			// technique binds, and stock fills it with an _sg: of 5,346 stock semantic-8 entries
			// 5,208 are named _sg (97.4%), against 72 $white and a scattering of one-offs. _sg is
			// BC3 with the specular in RGB and gloss in alpha - see the channel recipe in
			// docs/iw7-packed-textures.md.
			//
			// Nothing here packs two sources together. The pixels are the IW5 specular re-shaped
			// in place, which IwiImage.cpp already does correctly for both source formats: a DXT5
			// specular is already the _sg layout, because IW3's material compiler merged the cos
			// map into its alpha, and a DXT1 specular is transcoded up to BC3 with an alpha block
			// added. Only the *name* was missing, so a converted material pointed its specular
			// slot at a raw IW5 name instead of an IW7 one.

			// IW7 names its unpacked maps off one shared base - camo_97_c, camo_97_n, camo_97_sg.
			// IW5 and IW3 spell the specular differently, so recover that base before appending
			// IW7's suffix:
			//
			//   foo_spc / foo_spec / foo_s                -> foo
			//   ~foo_spec-rgb&foo_cos-l-11 (IW3 merged)   -> foo
			//
			// Anything unrecognised keeps its whole name, which just yields <name>_sg. Stripping
			// _sg as well makes this idempotent, so a source that is already IW7-named survives a
			// round trip unchanged.
			std::string iw7_map_base(const std::string& name)
			{
				auto base = name;

				// IW3's material compiler emits "~<spec>-rgb&<cos>-l-11" for a merged spec+gloss
				// pair; the part before the first '-' or '&' is the specular's own name.
				if (!base.empty() && base.front() == '~')
				{
					base.erase(0, 1);
					const auto cut = base.find_first_of("-&");
					if (cut != std::string::npos)
					{
						base.resize(cut);
					}
				}

				static const char* const suffixes[] = { "_spec", "_spc", "_sg", "_s" };
				for (const auto* suffix : suffixes)
				{
					const auto len = std::strlen(suffix);
					if (base.size() > len && base.compare(base.size() - len, len, suffix) == 0)
					{
						base.resize(base.size() - len);
						break;
					}
				}

				return base;
			}

			std::unordered_map<std::string, std::string> unpacked_sg_cache;

			std::string dump_unpacked_sg(GfxImage* spec)
			{
				if (!spec || !spec->name)
				{
					return {};
				}

				const auto key = packed_cache_key(spec, nullptr);
				const auto cached = unpacked_sg_cache.find(key);
				if (cached != unpacked_sg_cache.end())
				{
					return cached->second;
				}

				std::string name;

				allocator mem;

				// Same order as the plain image dumper: prefer what the zone carries, and only go
				// to the filesystem when there is nothing resident. IW5 streams its model textures
				// as .iwi with no resident data; IW3 and IW4 keep them in texture.loadDef.
				auto* converted = IW7Converter::convert_resident(spec, mem);
				if (!converted)
				{
					converted = IW7Converter::convert_iwi(spec->name, spec->semantic, mem);
				}

				if (converted)
				{
					name = iw7_map_base(spec->name) + "_sg";

					// build_image named it after the source it read; this is the same pixels under
					// the name IW7 expects to find in the specular slot.
					converted->name = mem.duplicate_string(name);
					converted->semantic = IW7::TextureSemantic::TS_SPECULAR_MAP;

					IW7::IGfxImage::dump(converted);
				}

				unpacked_sg_cache[key] = name;
				return name;
			}
		}

		bool has_color_tint(const Material* asset)
		{
			static constexpr float identity[4] = { 1.0f, 1.0f, 1.0f, 1.0f };

			for (int i = 0; i < asset->constantCount; ++i)
			{
				const auto& constant = asset->constantTable[i];
				if (constant.nameHash == 3054254906u)
				{
					return !std::equal(std::begin(constant.literal), std::end(constant.literal), std::begin(identity));
				}
			}

			return false;
		}

		void dump(Material* asset, bool geotrail)
		{
			if (asset)
			{
				const auto has_ct = has_color_tint(asset);

				auto new_name = IW7::replace_material_prefix(asset->name, asset->techniqueSet ? asset->techniqueSet->name : "", geotrail, has_ct);
				auto c_name = clean_name(new_name);

				const auto path = "materials\\"s + new_name + ".json"s;
				auto file = zonetool::filesystem::file(path);

				ordered_json matdata;

				//matdata["name"] = new_name;

				std::string techset;
				std::string iw7_techset;
				if (asset->techniqueSet)
				{
					techset = asset->techniqueSet->name;

					bool result = false;
					iw7_techset = IW7::get_IW7_techset(techset, asset->name, &result, geotrail, has_ct);
					if (!result)
					{
						//ZONETOOL_ERROR("Not dumping material \"%s\"", asset->name);
						//return;
					}
					matdata["techniqueSet->original"] = techset;
					matdata["techniqueSet->name"] = iw7_techset;
				}

				// ---- IW7 base layer -------------------------------------------------------
				//
				// IW5 hands us colour, normal and specular as three separate maps. IW7 wants them
				// as two packed ones - _packed_cs at semantic 14 and _packed_ng at semantic 15 -
				// and that pairing is not optional: of 11,313 stock IW7 materials carrying
				// textures, only 247 use semantic 5 or 8 without 14/15 and every one of those is a
				// tools_* debug shader. The three-map arrangement only ever appears in IW7 as an
				// extra blend layer. See docs/iw7-packed-textures.md.
				//
				// The slot hashes are unchanged between the two games, so each entry keeps its
				// typeHash and only its semantic and image change.
				//
				// p0 is a statement about the *technique*, not about the images. A technique
				// decides for itself whether it takes packed textures and says so in its name:
				// l_sm_replace_i0c0s0n0p0 declares two slots, c@14 and n@15, while
				// l_sm_replace_i0c0s0n0 declares three, c@2 n@5 s@8. Across 3,473 native techsets
				// 3,433 appear with exactly one slot set, so the name pins it - and sub_140E3F220
				// binds arguments by scanning the material's table for each hash with no bounds
				// check, so getting the set wrong is a crash, not a glitch.
				//
				// So p0 governs exactly two things: which technique the material binds, and
				// whether the separate specular entry survives. It does not govern whether the
				// packed pair is built. The pair is always built and always dumped, under the
				// stock name - see packed_cs_name_for / packed_ng_name_for above - because the
				// packed base layer is what IW7 images look like whatever technique reads them.
				//
				// Only techsets whose p0 form is known to exist are listed here; everything else
				// keeps its three-slot technique, and its texture table keeps pointing at the
				// unpacked colour, normal and specular so the slot set still matches.
				// The packed target now lives in mapped_techsets, next to the technique it belongs
				// to, rather than in a second table keyed on the resolved IW7 name.
				//
				// Verified: both p0 forms exist under zonetool_paths (techsets_common and
				// techsets_global_core_mp), and stock materials on them carry exactly the two slots
				// written below - semantic 15 at typeHash 1507003663 pointing at a _packed_ng and
				// semantic 14 at 2695565377 pointing at a _packed_cs, with no specular entry
				// (asphalt_road_cracks, ch_ground_dirt03, ch_wall_floor_destroyed). IW7 also ships
				// this map's own 80s_econ car in mp_breakneck and packs it, so the packed target is
				// what the game itself does with this asset.
				// Two packed forms, and a techset has at most one of them. p0 is the opaque form;
				// pa0 adds the opacity map that a blend or alpha-test technique needs, because
				// _packed_cs has spent its own alpha on reflectance. Prefer pa0 wherever it is
				// registered - a techset only has one if its technique reads alpha.
				const auto packed_alpha_techset = IW7::get_packed_alpha_techset(techset, geotrail);
				const auto packed_techset = packed_alpha_techset.empty()
					? IW7::get_packed_techset(techset, geotrail)
					: packed_alpha_techset;
				const auto wants_alpha = !packed_alpha_techset.empty();
				const auto packable = !packed_techset.empty();

				// Which slot an entry is comes from its typeHash, not its semantic. IW5 files the
				// detail map under semantic 2 alongside the colour map, separated only by the hash,
				// so selecting on semantic picked whichever of the two came last in the table -
				// and since the table is ordered by hash and detailMap (3948059469) sorts after
				// colorMap (2695565377), that was always the detail map. mtl_metal_pail built its
				// entire packed base layer out of metal_01, its shared detail texture, instead of
				// pail, its albedo. Confirmed against CoD4's own raw/materials/mtl_metal_pail:
				// colorMap pail, detailMap metal_01, normalMap pail_bump, specularMap ~pail_spec.
				GfxImage* src_colour = nullptr;
				GfxImage* src_normal = nullptr;
				GfxImage* src_spec = nullptr;
				GfxImage* src_detail = nullptr;
				for (auto i = 0; i < asset->textureCount; i++)
				{
					if (asset->textureTable[i].semantic == 11 || !asset->textureTable[i].u.image)
					{
						continue;
					}
					switch (asset->textureTable[i].nameHash)
					{
					case slot_hash_colour: src_colour = asset->textureTable[i].u.image; break;
					case slot_hash_normal: src_normal = asset->textureTable[i].u.image; break;
					case slot_hash_spec:   src_spec   = asset->textureTable[i].u.image; break;
					case slot_hash_detail: src_detail = asset->textureTable[i].u.image; break;
					default: break;
					}
				}


				// Build the pair whenever there is anything to build it from. This is deliberately
				// not conditional on `packable`: gating it there meant a material on a techset
				// with no registered p0 form produced no _cs and no _ng at all, and with
				// no packed target registered that was every material.
				lazy_spec spec{ src_spec };
				const auto packed_cs_name = dump_packed_cs(src_colour, spec);
				const auto packed_ng_name = dump_packed_ng(src_normal, spec);

				// The unpacked counterpart of the specular. Built whether or not the material ends
				// up packed, for the same reason as the pair above: it is what semantic 8 holds in
				// IW7, and which technique the material lands on does not change that. A packed
				// material drops its specular entry, so this one goes unreferenced there.
				// Enabled: stock binds a real _sg here, never the raw IW3 combined name.
				//
				// 22 stock materials on this techset family use an IW3-shared asset, and every one
				// of them is sem 8 -> <base>_sg, sem 5 -> <base>_nml, sem 2 -> <base>_col
				// (mtl_mp_dart_dinerboothchair, mtl_life_preserver_256, mtl_dead_pine ...). Across
				// all of stock, 243 materials on 84 unpacked techsets use IW3 assets, so the
				// unpacked path is first-class for this content - it is not a fallback.
				//
				// iw7_map_base turns "~80s_econ_spc-rgb&80s_econ_cos-l-11" into "80s_econ_sg",
				// which is exactly the name stock would use. Same pixels either way - a DXT5
				// combined specular already is a BC3 with gloss in alpha - so this is about the
				// name and semantic the slot is filled with, not the content.
				const auto unpacked_sg_name = dump_unpacked_sg(src_spec);

				// Repointing the material at the pair is the part p0 does gate. Both halves have
				// to have landed, or the slot set will not match the p0 technique.
				// The opacity map, only for a pa0 target. Built from the colour, so it needs the
				// same source the _cs came from.
				const auto packed_a_name = wants_alpha ? dump_packed_a(src_colour) : std::string{};

				// Repointing the material at the pair is the part p0 does gate. Both halves have
				// to have landed, or the slot set will not match the p0 technique. A pa0 target
				// needs all three: its technique binds semantic 16 by hash like any other slot,
				// so arriving there without one is the same out-of-bounds read as a missing
				// _packed_ng. Falling back to the unpacked technique is the safe failure.
				// A d0 technique binds semantic 3 from the material's own detail map - there is no
				// packed half to fall back on, and required_slots only covers the unpacked targets,
				// so the packed d0 form is the one place a missing detail map would leave a slot
				// unbound. Staying on the unpacked technique is safe: its required_slots entry
				// fills the detail slot with a placeholder.
				const auto packed_wants_detail = packed_techset.find("d0") != std::string::npos;
				const auto packed = packable && !packed_cs_name.empty() && !packed_ng_name.empty()
					&& (!wants_alpha || !packed_a_name.empty())
					&& (!packed_wants_detail || src_detail != nullptr);
				if (packed)
				{
					iw7_techset = packed_techset;
					matdata["techniqueSet->name"] = iw7_techset;
				}


				// gameFlags: IW5 bit 0x40 is IW7 bit 0x80.
				//
				// Across all 54,708 stock IW7 materials, gameFlags bit 0x40 is set exactly zero
				// times, while 0x80 is set on 73.4% of them. Carrying IW5's value verbatim gave
				// 0x50 where every one of the 131 stock materials on mo_l_sm_replace_i0c0s0n0
				// has 0x90, and 0x52 where the wc_ ones have 0x92 - the same bit, in both
				// families. Moving it lands on stock's value exactly.
				{
					auto game_flags = asset->info.gameFlags;
					if (game_flags & 0x40)
					{
						game_flags = static_cast<decltype(game_flags)>((game_flags & ~0x40) | 0x80);
					}
					matdata["gameFlags"] = game_flags;
				}
				matdata["unkFlags"] = 0; // idk
				matdata["sortKey"] = IW7::get_IW7_sortkey(asset->info.sortKey, asset->name, iw7_techset);
				matdata["renderFlags"] = IW7::get_render_flags_by_techset(iw7_techset); // idk

				matdata["textureAtlasRowCount"] = asset->info.textureAtlasRowCount;
				matdata["textureAtlasColumnCount"] = asset->info.textureAtlasColumnCount;
				matdata["textureAtlasFrameBlend"] = 0;
				matdata["textureAtlasAsArray"] = 0;

				matdata["surfaceTypeBits"] = asset->info.surfaceTypeBits; // convert
				// hashIndex;

				// stateFlags: 0x40 is 2d-only in IW7.
				//
				// Of the 2,766 stock materials that set it, every single one is on a 2d techset
				// (2d, 2d|_evc, 2d|_nofog, 2d|_ct ...), and 2,440 of those carry 0x40 and nothing
				// else. It never appears on a world or model techset. IW5 uses the bit for
				// something else, and carrying it across produced 0x79 on mp_test_h1's models -
				// a value that occurs zero times in stock, against 0x39 on 125 of the 131 stock
				// materials sharing that techset. Stripping it gives exactly 0x39.
				//
				// Same class of bug as the H1 and IW6 dumpers already handle for bit 0x2, which
				// means something different in IW4 than in IW5.
				{
					auto state_flags = asset->stateFlags;
					const auto is_2d = iw7_techset.compare(0, 2, "2d") == 0;
					if (!is_2d)
					{
						state_flags = static_cast<decltype(state_flags)>(state_flags & ~0x40);
					}
					matdata["stateFlags"] = state_flags;
				}
				matdata["cameraRegion"] = IW7::get_IW7_camera_region(asset->cameraRegion, asset->name, iw7_techset);
				matdata["materialType"] = IW7::get_material_type_from_techset(iw7_techset);
				matdata["assetFlags"] = 0; // IW7::MTL_ASSETFLAG_NONE;

				// fixes
				//if (matdata["cameraRegion"].get<uint8_t>() == 4 && matdata["sortKey"].get<uint8_t>() != 41 && iw7_techset.starts_with("2d"))
				//{
				//	matdata["cameraRegion"] = 11;
				//}

				// an array from the start: CONSTANT_TABLE_ADD_IF_NOT_FOUND inserts into it, which throws on null
				// (particle_cloud materials carry no constants of their own but need textureAtlas)
				ordered_json constant_table = ordered_json::array();
				for (int i = 0; i < asset->constantCount && techset != "2d"; i++)
				{
					ordered_json table;
					std::string constant_name = asset->constantTable[i].name;
					const auto constant_hash = asset->constantTable[i].nameHash;

					if (constant_name.size() > 12)
					{
						constant_name.resize(12);
					}

					if (constant_hash == 1033475292) // envMapParms
					{
						continue;
					}

					table["name"] = constant_name.data();
					table["nameHash"] = constant_hash;

					nlohmann::json literal_entry;
					literal_entry[0] = asset->constantTable[i].literal[0];
					literal_entry[1] = asset->constantTable[i].literal[1];
					literal_entry[2] = asset->constantTable[i].literal[2];
					literal_entry[3] = asset->constantTable[i].literal[3];
					table["literal"] = literal_entry;

					constant_table[constant_table.size()] = table;
				}

#define CONSTANT_TABLE_ADD_IF_NOT_FOUND(CONST_NAME, CONST_HASH, LITERAL_1, LITERAL_2, LITERAL_3, LITERAL_4) \
				bool has_const = false; \
				std::size_t insert_position = constant_table.size(); \
				for (std::size_t i = 0; i < constant_table.size(); i++) \
				{ \
					if (constant_table[i]["nameHash"].get<std::size_t>() == CONST_HASH) \
					{ \
						has_const = true; \
						break; \
					} \
					if (constant_table[i]["nameHash"].get<std::size_t>() > CONST_HASH) \
					{ \
						insert_position = i; \
						break; \
					} \
				} \
				if (!has_const) \
				{ \
					ordered_json table; \
					table["name"] = CONST_NAME; \
					table["nameHash"] = CONST_HASH; \
					nlohmann::json literal_entry; \
					literal_entry[0] = LITERAL_1; \
					literal_entry[1] = LITERAL_2; \
					literal_entry[2] = LITERAL_3; \
					literal_entry[3] = LITERAL_4; \
					table["literal"] = literal_entry; \
					constant_table.insert(constant_table.begin() + insert_position, table); \
				}

				if (iw7_techset.find("s0") != std::string::npos)
				{
					CONSTANT_TABLE_ADD_IF_NOT_FOUND("reflectionRa", 3344177073u, 8096.0f, 0.0f, 0.0f, 0.0f);
				}
				if (iw7_techset.find("_lin") != std::string::npos && !iw7_techset.starts_with("particle_cloud_"))
				{
					CONSTANT_TABLE_ADD_IF_NOT_FOUND("textureAtlas", 1128936273u,
						static_cast<float>(asset->info.textureAtlasColumnCount), static_cast<float>(asset->info.textureAtlasRowCount), 1.0f, 1.0f);
				}
				if (iw7_techset.find("_evc") != std::string::npos)
				{
					CONSTANT_TABLE_ADD_IF_NOT_FOUND("colorIntensi", 3670886770, 1.0f, 0.0f, 0.0f, 0.0f);
				}
				if (iw7_techset.find("_ct") != std::string::npos || iw7_techset == "2d" || iw7_techset == "wc_unlit_blend_lin_ndw")
				{
					CONSTANT_TABLE_ADD_IF_NOT_FOUND("colorTint", 3054254906u, 1.0f, 1.0f, 1.0f, 1.0f);
				}

				matdata["constantTable"] = constant_table;

				ordered_json material_images;
				for (auto i = 0; i < asset->textureCount; i++)
				{
					ordered_json image;
					if (asset->textureTable[i].semantic == 11)
					{
						auto* water = asset->textureTable[i].u.water;
						if (water->image && water->image->name)
						{
							image["image"] = water->image->name;
						}
						else
						{
							image["image"] = "";
						}
					}
					else
					{
						if (asset->textureTable[i].u.image && asset->textureTable[i].u.image->name)
						{
							image["image"] = asset->textureTable[i].u.image->name;
						}
						else
						{
							image["image"] = "";
						}
					}

					// Point the base layer at the packed pair. Some IW5 decals carry semantic 0
					// even for colorMap/normalMap, so identify these slots by their stable hashes.
					// The p0 technique declares exactly
					// two slots, c@14 and n@15, so the specular slot goes away with it - its image
					// has been consumed into both halves.
					//
					// This is `packed`, not "a packed name exists": the images are built for every
					// material, but a material still on a three-slot technique has to keep
					// pointing at the unpacked colour, normal and specular, because that technique
					// binds all three hashes and would walk off the end of a two-entry table.
					const auto iw5_semantic = asset->textureTable[i].semantic;
					const auto slot_hash = asset->textureTable[i].nameHash;

					// The detail map rides at semantic 2 in IW5 and is told apart from the colour
					// map only by its hash, so it has to be caught before the colour branch below
					// or it is repointed at the packed pair and lost. IW7 reads it at semantic 3
					// on both the packed and unpacked forms (412 stock materials, typeHash
					// 3948059469, 'd'..'p'), and it keeps the image it arrived with.
					//
					// Setting this is safe whether or not the material lands on a d0 technique: a
					// technique binds the hashes it declares and ignores the rest, so on a
					// non-d0 target the entry simply goes unread.
					if (slot_hash == slot_hash_detail)
					{
						asset->textureTable[i].semantic = IW7::TextureSemantic::TS_DETAIL_MAP;
					}
					else if (packed && slot_hash == slot_hash_colour)
					{
						image["image"] = packed_cs_name;
						asset->textureTable[i].semantic = IW7::TextureSemantic::TS_COLOR_SPECULAR_MAP;
					}
					else if (packed && slot_hash == slot_hash_normal)
					{
						image["image"] = packed_ng_name;
						asset->textureTable[i].semantic = IW7::TextureSemantic::TS_NORMAL_OCCLUSSION_GLOSS_MAP;
					}
					else if (packed && slot_hash == slot_hash_spec)
					{
						continue;   // the p0 technique has no separate specular slot
					}
					else if (slot_hash == slot_hash_spec && !unpacked_sg_name.empty())
					{
						// Unpacked, so the specular slot survives - point it at the _sg rather
						// than at the raw IW5 name. Same slot, same typeHash, same semantic; only
						// the image changes, to the one IW7 expects to find here.
						image["image"] = unpacked_sg_name;
						asset->textureTable[i].semantic = IW7::TextureSemantic::TS_SPECULAR_MAP;
					}
					else if (slot_hash == slot_hash_colour)
					{
						asset->textureTable[i].semantic = IW7::TextureSemantic::TS_COLOR_MAP;
					}
					else if (slot_hash == slot_hash_normal)
					{
						asset->textureTable[i].semantic = IW7::TextureSemantic::TS_NORMAL_MAP;
					}
					else if (slot_hash == slot_hash_spec)
					{
						asset->textureTable[i].semantic = IW7::TextureSemantic::TS_SPECULAR_MAP;
					}
					else
					{
						asset->textureTable[i].semantic = IW7::convert_semantic(iw5_semantic);
					}

					image["semantic"] = asset->textureTable[i].semantic;
					image["samplerState"] = asset->textureTable[i].samplerState == 11 ? 19 : asset->textureTable[i].samplerState; // convert? ( should be fine )
					image["lastCharacter"] = asset->textureTable[i].nameEnd;
					image["firstCharacter"] = asset->textureTable[i].nameStart;
					image["typeHash"] = asset->textureTable[i].nameHash;

					// add image data to material
					material_images.push_back(image);
				}

#define IMAGE_ADD_IF_NOT_FOUND(IMAGE, SEMANTIC, SAMPLER_STATE, LAST_CHARACTER, FIRST_CHARACTER, HASH) \
				bool has_image = false; \
				std::size_t insert_position = material_images.size(); \
				for (std::size_t i = 0; i < material_images.size(); i++) \
				{ \
					if (material_images[i]["typeHash"].get<std::size_t>() == HASH) \
					{ \
						has_image = true; \
						break; \
					} \
					if (material_images[i]["typeHash"].get<std::size_t>() > HASH) \
					{ \
						insert_position = i; \
						break; \
					} \
				} \
				if (!has_image) \
				{ \
					ordered_json image; \
					image["image"] = IMAGE; \
					image["semantic"] = SEMANTIC; \
					image["samplerState"] = SAMPLER_STATE; \
					image["lastCharacter"] = LAST_CHARACTER; \
					image["firstCharacter"] = FIRST_CHARACTER; \
					image["typeHash"] = HASH; \
					material_images.insert(material_images.begin() + insert_position, image); \
				}

				// Fill in whatever the technique declares and the source material did not supply.
				// This is not cosmetic: sub_140E3F220 walks the texture table looking for each
				// argument's hash and never checks for the end of it, so one absent slot sends it
				// off into unmapped memory.
				//
				// Every slot set below was read off a native IW7 material using that technique, and
				// the placeholders are the ones stock uses for the same purpose - $identitynormalmap
				// at sem 5 (254 native materials), $white at sem 8 (66), $black at the layer-1
				// colour (50). Note lastCharacter encodes the layer index, so a layer-1 slot ends
				// in '1' (49) rather than 'p' (112).
				struct required_slot
				{
					const char* image;
					std::uint8_t semantic;
					std::uint8_t sampler;
					std::uint8_t last_character;
					std::uint8_t first_character;
					unsigned int hash;
				};

				static const required_slot slot_colour  { "$white", 2, 19, 112, 99, 2695565377 };
				static const required_slot slot_normal  { "$identitynormalmap", 5, 1, 112, 110, 1507003663 };
				static const required_slot slot_spec    { "$zero", 8, 19, 112, 115, 887934131 };
				static const required_slot slot_occl    { "$zero", 9, 19, 112, 115, 2771134132 };
				static const required_slot slot_layer1  { "$black", 2, 19, 49, 99, 3054311504 };
				// Defensive only: a d0 target is chosen because the IW3 name carries d0, which means
				// the source has a detail map, so this should never fire. Stock has no placeholder
				// to copy here - $identitydetailmap does not exist and no stock d0 material lacks a
				// detail map - so $gray is a judgement call: mid-grey is neutral under an overlay
				// blend and merely darkens under a multiply, which fails quieter than $white would.
				static const required_slot slot_detail  { "$gray", 3, 19, 112, 100, slot_hash_detail };

				static const std::unordered_map<std::string, std::vector<required_slot>> required_slots =
				{
				// generated: the slots each target binds, read off the stock materials that
				// ship on it. A technique binds by hash with no bounds check, so any slot the
				// source has no texture for has to be filled rather than left out.
					{"mo_l_sm_atest_i0c0",                    {slot_colour, slot_normal}},
					{"mo_l_sm_atest_i0c0n0",                  {slot_colour, slot_normal}},
					{"mo_l_sm_atest_i0c0s0",                  {slot_colour, slot_normal, slot_spec}},
					{"mo_l_sm_atest_i0c0s0n0",                {slot_colour, slot_normal, slot_spec}},
					{"mo_l_sm_atest_i0c0s0n0_nocast",         {slot_colour, slot_normal, slot_spec}},
					{"mo_l_sm_ndw_blend_i0c0",                {slot_colour, slot_normal}},
					{"mo_l_sm_ndw_blend_i0c0n0",              {slot_colour, slot_normal}},
					{"mo_l_sm_ndw_blend_i0c0s0",              {slot_colour, slot_normal, slot_spec}},
					{"mo_l_sm_ndw_blend_i0c0s0n0",            {slot_colour, slot_normal, slot_spec}},
					{"mo_l_sm_replace_i0c0",                  {slot_colour, slot_normal}},
					{"mo_l_sm_replace_i0c0n0",                {slot_colour, slot_normal}},
					{"mo_l_sm_replace_i0c0n0d0",              {slot_colour, slot_detail, slot_normal}},
					{"mo_l_sm_replace_i0c0s0",                {slot_colour, slot_normal, slot_spec}},
					{"mo_l_sm_replace_i0c0s0n0",              {slot_colour, slot_normal, slot_spec}},
					{"mo_l_sm_replace_i0c0s0n0d0",            {slot_colour, slot_detail, slot_normal, slot_spec}},
					{"wc_l_sm_atest_i0c0",                    {slot_colour, slot_normal}},
					{"wc_l_sm_atest_i0c0s0",                  {slot_colour, slot_normal, slot_spec}},
					{"wc_l_sm_ndw_blend_i0c0",                {slot_colour, slot_normal}},
					{"wc_l_sm_ndw_blend_i0c0n0",              {slot_colour, slot_normal}},
					{"wc_l_sm_ndw_blend_i0c0s0",              {slot_colour, slot_normal, slot_spec}},
					{"wc_l_sm_ndw_blend_i0c0s0n0",            {slot_colour, slot_normal, slot_spec}},
					{"wc_l_sm_replace_i0c0",                  {slot_colour, slot_normal}},
					{"wc_l_sm_replace_i0c0n0",                {slot_colour, slot_normal}},
					{"wc_l_sm_replace_i0c0s0",                {slot_colour, slot_normal, slot_spec}},
					{"wc_l_sm_replace_i0c0s0n0",              {slot_colour, slot_normal, slot_spec, slot_occl}},

					// hand-written: targets the generator does not produce.
					{"mo_l_sm_replace_i0c0s0n0p0",      {}},   // the packed pair is written directly
					{"w_l_sm_replace_r0c0_m1c1",        {slot_colour, slot_normal, slot_layer1}},
					{"w_l_sm_replace_r0c0nl0_m1c1",     {slot_colour, slot_normal, slot_layer1}},
					{"w_l_sm_blend_b0c0sl0ol0_m1c1",    {slot_colour, slot_normal, slot_spec, slot_occl, slot_layer1}},
				};

				const auto required = required_slots.find(iw7_techset);
				if (required != required_slots.end())
				{
					for (const auto& slot : required->second)
					{
						auto insert_at = material_images.size();
						auto present = false;
						for (std::size_t i = 0; i < material_images.size(); i++)
						{
							const auto hash = material_images[i]["typeHash"].get<std::size_t>();
							if (hash == slot.hash)
							{
								present = true;
								break;
							}
							if (hash > slot.hash)
							{
								insert_at = i;
								break;
							}
						}
						if (present)
						{
							continue;
						}

						ordered_json entry;
						entry["image"] = slot.image;
						entry["semantic"] = slot.semantic;
						entry["samplerState"] = slot.sampler;
						entry["lastCharacter"] = slot.last_character;
						entry["firstCharacter"] = slot.first_character;
						entry["typeHash"] = slot.hash;
						material_images.insert(material_images.begin() + insert_at, entry);
					}
				}
				else if (iw7_techset.find("n0") != std::string::npos)
				{
					IMAGE_ADD_IF_NOT_FOUND("$identitynormalmap", 5, 1, 112, 110, 1507003663);
				}

				// The pa0 opacity slot. It is added rather than remapped because no IW5 semantic
				// corresponds to it - the source keeps its opacity inside the colour map's alpha,
				// which the packed pair cannot carry - so there is no existing entry to repoint.
				//
				// Same hash as the specular-occlusion slot (2771134132, 's'..'p'); the technique
				// decides how it is read, which is why it arrives as semantic 16 here and 9 on an
				// occlusion technique. Field values are stock's: samplerState 19 on 2221 of the
				// 2519 stock pa0 materials.
				if (packed && wants_alpha && !packed_a_name.empty())
				{
					constexpr unsigned int alpha_hash = 2771134132;

					auto insert_at = material_images.size();
					auto present = false;
					for (std::size_t i = 0; i < material_images.size(); i++)
					{
						const auto hash = material_images[i]["typeHash"].get<std::size_t>();
						if (hash == alpha_hash)
						{
							present = true;
							break;
						}
						if (hash > alpha_hash)
						{
							insert_at = i;
							break;
						}
					}

					if (!present)
					{
						ordered_json entry;
						entry["image"] = packed_a_name;
						entry["semantic"] = IW7::TextureSemantic::TS_ALPHA_REVEAL_THICKNESS_MAP;
						entry["samplerState"] = 19;
						entry["lastCharacter"] = 112;
						entry["firstCharacter"] = 115;
						entry["typeHash"] = alpha_hash;
						material_images.insert(material_images.begin() + insert_at, entry);
					}
				}

				matdata["textureTable"] = material_images;

				auto str = matdata.dump(4, ' ', true, nlohmann::detail::error_handler_t::replace);

				matdata.clear();

				file.open("wb");
				file.write(str);
				file.close();
			}
		}
	}
}
