name: Build
permissions:
  contents: write

on:
  push:
    branches:
      - "x64"
      - "x64-cleanup"
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build zonetool
    runs-on: windows-2022
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} zonetool
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=Win32 build/zonetool.sln

      - name: Upload ${{matrix.configuration}} artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}} zonetool
          path: |
            build/bin/Win32/${{matrix.Configuration}}/ZoneTool.dll
            build/bin/Win32/${{matrix.configuration}}/ZoneTool.pdb

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Download Debug artifacts
        uses: actions/download-artifact@v4
        with:
          name: Debug zonetool
          path: Debug

      - name: Download Release artifacts
        uses: actions/download-artifact@v4
        with:
          name: Release zonetool
          path: Release

      - name: Zip Debug zonetool
        run: |
          cd Debug
          zip -r ../"Debug zonetool.zip" .

      - name: Zip Release zonetool
        run: |
          cd Release
          zip -r ../"Release zonetool.zip" .

      - name: Delete old release/tag if exists
        run: |
          gh release delete latest -y || true
          git push origin :refs/tags/latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new release
        run: |
          gh release create latest "Debug zonetool.zip" "Release zonetool.zip" \
            --title "Latest Build" \
            --notes "This build was automated from ${{ github.sha }}. If you are unsure which zonetool to use, download **Release zonetool.zip**. If you are crashing and need to debug, use **Debug zonetool.zip**."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
